services:

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://analytics_user:analytics_pass@postgres:5432/analytics
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: python worker.py
    environment:
      DATABASE_URL: postgresql://analytics_user:analytics_pass@postgres:5432/analytics
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: